# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e70ab305719ff2a4eaac7e06add020180b774046e2a1e2bc9c4b142555778557e4eb1c835a0925e918fc0996998103910ee235254f6616bc4468d1a2cbfe95ce

test:
  secret_key_base: 28652105b15985a5c576f65e24c58dce7a7a7e1b948531ca165e11dcf243617658c0dac45927702443ae3b64d3a38393a820c4a15de94da119bb07647c79632e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
